CREATE PROCEDURE Inventory.GetHelpDoc(@Key UNIQUEIDENTIFIER)

AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	
	SELECT BLB.Blob AS HelpDoc from Inventory.SwPackageBlobsMap SWPKG
	INNER JOIN
	Inventory.Blobs AS BLB
	ON 
	SWPKG.BlobUID = BLB.BlobUID
	WHERE SWPKG.SwPkgUID = @Key and BLB.BlobTypeUID = 'B1CD7C3D-DA88-4608-834B-86F388813D8C'
END